compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED
machine_rank: 0
main_process_ip: localhost
main_process_port: 12355
main_training_function: main
num_machines: 1
num_processes: 2
use_cpu: false
fsdp_config: {}
mixed_precision: "no"
deepspeed_config:
 gradient_clipping: 1.0
 offload_optimizer_device: none
 offload_param_device: none
 zero3_init_flag: true
 zero_stage: 2